#####################################
##          全サーバ共通           ##
#####################################
- name: apply configuration to target nodes
  hosts: target
#  remote_user: vagrant
  remote_user: root
  become: yes
  roles:
    - common
    - awx
